### ISSUE TITLE
No movement?

### ISSUE THREAD

**Issue by PatrickHackett** [matthiasbroske/GPUStableFluids#1]
With a fresh download, open in Unity, and run, I'm not seeing any movement in the 2d or 3d samples.
I can interact with the scenes and I don't seem to see any errors.
I'm on Windows 10.

**Comment by matthiasbroske** [comment]
Thanks for pointing this out -- should be fixed now!

The issue seems to have something to do with binding a single texture to multiple texture inputs in a compute shader. Works fine on Metal, but apparently not so fine on Direct3D11...

**Comment by PatrickHackett** [comment]
Nice work! The 3d visualization is gorgeous, btw!
